name: Build Docker Image

on: [push]
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
          - name: Login into Dockerhub
            uses: docker/login-action@v3
            with:
              username: ${{secrets.DH_USERNAME}}
              password: ${{secrets.DH_PASSWORD}}

          - name: Set up QEMU
            uses: docker/setup-qemu-action@v3

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

          - name: Build and push tag
            if: ${{ github.ref_type == 'tag' }}
            id: docker_build_tag
            uses: docker/build-push-action@v6
            with:
              push: true
              tags: rk90/alpine-hugo-firebase:${{ github.ref_name }}
              platforms: linux/amd64

          - name: Build and push latest
            if: ${{ github.ref_type == 'branch' }}
            id: docker_build_latest
            uses: docker/build-push-action@v6
            with:
              push: true
              tags: rk90/alpine-hugo-firebase:latest
              platforms: linux/amd64
